@startuml
' Classes for the domain
class Animal {
  +int id
  +String name
  +Animal(Breed breed, Owner owner)
}

class Owner {
  +int id
  +String name
  +String address
  +String phone
}

class Appointment {
  +DateTime startAt
  +Appointment(Animal animal, Physician physician)
}

class Physician {
  +int id
  +String name
  +String address
  +String phone
}

class Breed {
  +String name
  +Breed(String name)
}

class Condition {
  +String commonName
  +String scientificName
  +Condition(String commonName, String scientificName)
}

' Associations
Animal "1" -- "1" Owner : isOwnedBy
Animal "0..1" -- "1" Breed : has
Appointment "1" -- "1" Animal : attendedFor
Appointment "1" -- "1" Physician : handledBy

' Many-to-Many association between Breed and Condition. 
' A breed may have several common conditions, and the same condition
' may be common in several different breeds.
Breed "0..*" -- "0..*" Condition : commonConditions

@enduml