@startuml
actor Member

usecase "Subscribe" as UC_Subscribe
usecase "Unsubscribe" as UC_Unsubscribe
usecase "Borrow Book" as UC_Borrow
usecase "Return Book" as UC_Return
usecase "Extend Loan" as UC_Extend
usecase "View Borrowed Books" as UC_View

Member --> UC_Subscribe
Member --> UC_Unsubscribe
Member --> UC_Borrow
Member --> UC_Return
Member --> UC_Extend
Member --> UC_View
@enduml