@startuml
' Define classes

class Member {
  +firstName: String
  +surname: String
}

class Patron

class Library {
  +documents: Set<Document>
  +patrons: Set<Patron>
}

class Document {
  +title: String
}

class Journal extends Document {
  +dateOfPublication: Date
}

class Volume extends Document {
  +author: String
}

class Dictionary extends Volume

class Book extends Volume

class Comic extends Volume {
  +recipientName: String
}

' Relationships

Library "1" o-- "*" Document
Library "1" o-- "*" Patron

@enduml